services:
  api:
    image: local/taskmanagement-api:latest
    build:
      context: ./src
      dockerfile: TaskManagementSys.Api/Dockerfile
    ports:
      - "5000:80"
    env_file:
      - ./.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Data Source=/app/database/taskmanagement.db;Cache=Shared
    volumes:
      - ./database:/app/database
      - ./src:/src
    networks:
      - taskmanagement-network
    restart: unless-stopped

  blazorui:
    image: local/taskmanagement-blazorui:latest
    build:
      context: ./src
      dockerfile: TaskManagementSys.BlazorUI/Dockerfile
      target: dev
    ports:
      - "5010:80"
    env_file:
      - ./.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - API_URL=http://api:80
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
      - DOTNET_MODIFIABLE_ASSEMBLIES=Prefered
    volumes:
      - ./src:/src
    depends_on:
      - api
    networks:
      - taskmanagement-network
    restart: unless-stopped

networks:
  taskmanagement-network:
    driver: bridge

volumes:
  data: