services:
  api:
    image: local/taskmanagement-api:latest
    build:
      context: ./src
      dockerfile: TaskManagementSys.Api/Dockerfile
    ports:
      - "${API_PORT}:80"
    env_file:
      - ./.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - CONNECTION_STRING=Data Source=/app/database/taskmanagement.db
    volumes:
      - ./database:/app/database
    networks:
      - taskmanagement-network
    restart: unless-stopped

  blazorui:
    image: local/taskmanagement-blazorui:latest
    build:
      context: ./src
      dockerfile: TaskManagementSys.BlazorUI/Dockerfile
    ports:
      - "${BLAZOR_PORT}:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ApiBaseUrl=http://api:80
    depends_on:
      - api
    networks:
      - taskmanagement-network
    restart: unless-stopped

networks:
  taskmanagement-network:
    driver: bridge

volumes:
  data: